package ventanas;

import java.awt.Image;
import java.awt.Toolkit;

public class Interfaz extends javax.swing.JFrame {

   
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        salir.setFocusable(false);
        primButton.setFocusable(false);
        djikstraButton.setFocusable(false);
        recursivosButton.setFocusable(false);
        divideButton.setFocusable(false);
    }
    @Override
    public Image getIconImage(){
	Image retValue;
        retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/unicaribeIcono.gif"));
	return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        tittle2 = new javax.swing.JLabel();
        primButton = new javax.swing.JButton();
        djikstraButton = new javax.swing.JButton();
        tittle1 = new javax.swing.JLabel();
        recursivosButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setBackground(new java.awt.Color(51, 153, 255));
        salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/image.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 90, 40));

        tittle2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tittle2.setForeground(new java.awt.Color(255, 255, 255));
        tittle2.setText("Algoritmos recursivos");
        getContentPane().add(tittle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 270, 40));

        primButton.setBackground(new java.awt.Color(153, 153, 255));
        primButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        primButton.setForeground(new java.awt.Color(255, 255, 255));
        primButton.setText("Prim");
        primButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primButtonActionPerformed(evt);
            }
        });
        getContentPane().add(primButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 230, 100));

        djikstraButton.setBackground(new java.awt.Color(153, 153, 255));
        djikstraButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        djikstraButton.setForeground(new java.awt.Color(255, 255, 255));
        djikstraButton.setText("Djikstra");
        getContentPane().add(djikstraButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 230, 100));

        tittle1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tittle1.setForeground(new java.awt.Color(255, 255, 255));
        tittle1.setText("Algoritmos con Grafos");
        getContentPane().add(tittle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 270, 40));

        recursivosButton.setBackground(new java.awt.Color(153, 153, 255));
        recursivosButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        recursivosButton.setForeground(new java.awt.Color(255, 255, 255));
        recursivosButton.setText("<html><center>Abrir Algoritmos Recursivos</center></html>");
        recursivosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recursivosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(recursivosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 230, 100));

        divideButton.setBackground(new java.awt.Color(153, 153, 255));
        divideButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        divideButton.setForeground(new java.awt.Color(255, 255, 255));
        divideButton.setText("<html><center>Algoritmos divide y venceras</center></html>");
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });
        getContentPane().add(divideButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 230, 100));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void primButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primButtonActionPerformed

    private void recursivosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recursivosButtonActionPerformed
       AlgoritmosRecursivos nuevaInterfaz = new AlgoritmosRecursivos();
       nuevaInterfaz.setVisible(true);
    }//GEN-LAST:event_recursivosButtonActionPerformed

    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonActionPerformed
       AlgoritmosDivideYVenceras nuevaInterfaz = new AlgoritmosDivideYVenceras();
       nuevaInterfaz.setVisible(true);
    }//GEN-LAST:event_divideButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton divideButton;
    private javax.swing.JButton djikstraButton;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel logo;
    private javax.swing.JButton primButton;
    private javax.swing.JButton recursivosButton;
    private javax.swing.JButton salir;
    private javax.swing.JLabel tittle1;
    private javax.swing.JLabel tittle2;
    // End of variables declaration//GEN-END:variables
}
